kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: v2board-nfs
  namespace: v2b-k8s
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: v2board-nfs-pvc
  storageClassName: ''
  volumeMode: Filesystem
